<?php
require_once '../model/user.php';
require_once '../model/database.php';
require_once "../model/report.php";
$user = $this->user;
$tickets = $this->tickets;
// var_dump($user);
$mindate = null;
$maxdate = null;
?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <!--  This file has been downloaded from bootdey.com @bootdey on twitter -->
    <!--  All snippets are MIT license http://bootdey.com/license -->
    <title><?php echo $this->name; ?></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script> -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.1/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.1/dist/js/bootstrap.bundle.min.js"></script>
</head>

<body class="container">
    <h1><?php echo $this->name; ?> - Report <?php echo $this->id; ?></h1>
    <h2> Generated By: <?php echo $this->user->displayName                                 ; ?> </h2>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
    </a>
    <div class="d-flex justify-content-between align-items-center">
        <div><i class="fa fa-tag mr-1 text-muted"></i>
            <div class="d-inline-block font-weight-medium text-uppercase">My Tickets</div>
        </div>
        </a>
    </div>

    <div class="table-responsive">
        <table class="table table-hover mb-0">
            <thead>
                <tr>
                    <th>Ticket ID</th>
                    <th>Ticket Title</th>
                    <th>Ticket Author</th>
                    <th>Date Issued</th>
                    <th>Primary Service</th>
                    <th>Status</th>
                    <th>Priority</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($tickets as $ticket) { ?>
                    <?php
                        if ($mindate == null || $ticket->dateCreated < $mindate) $mindate = $ticket->dateCreated;
                        if ($maxdate == null || $ticket->dateCreated > $maxdate) $maxdate = $ticket->dateCreated;
                    ?>
                    <tr>
                        <td>
                            <!-- <a class="navi-link" href="../controller/manageTicket.php?ticket_id=<?php echo ($ticket->id); ?>" data-toggle="modal">7<?php echo ($ticket->id) ?></a> -->
                            <form action="../controller/editTicket.php" method="get">
                                <input type="submit" name="ticket_id" value="<?php echo ($ticket->id); ?>">
                            </form>
                        </td>
                        <td><?php echo ($ticket->title) ?></td>
                        <td><?php echo ($ticket->author->displayName); ?></td>
                        <td><?php echo ($ticket->dateCreated) ?></td>
                        <td><?php echo ($ticket->service->name); ?></td>
                        <?php if ($ticket->status->id() === 13) { ?>
                            <td><span class="badge badge-danger m-0"><?php echo ($ticket->status->name()) ?></span></td>
                        <?php } elseif ($ticket->status->id() === 3 || $ticket->status->id() === 4) { ?>
                            <td><span class="badge badge-info m-0"><?php echo ($ticket->status->name()) ?></span></td>
                        <?php } else { ?>
                            <td><span class="badge badge-success m-0"><?php echo ($ticket->status->name()) ?></span></td>
                        <?php } ?>

                        <?php if ($ticket->priority->id() === 3) { ?>
                            <td><span class="badge badge-danger m-0"><?php echo ($ticket->priority->name()) ?></span></td>
                        <?php } elseif ($ticket->priority->id() === 1) { ?>
                            <td><span class="badge badge-success m-0"><?php echo ($ticket->priority->name()) ?></span></td>
                        <?php } else {  ?>
                            <td><span class="badge badge-info m-0"><?php echo ($ticket->priority->name()) ?></span></td>
                        <?php } ?>
                    </tr>
                <?php  } ?>
            </tbody>
        </table>
        <h3>Number of Rows: <?php echo sizeof($tickets); ?></h3>
        <h4><?php echo ("Issued from $mindate to $maxdate"); ?></h4>
        <h4>
            <table>
                <?php foreach (LookupTable::fetch("status") as $status) { ?>
                    <?php 
                        [$id, $name] = $status;
                        $count = 0; 
                    ?>
                    <?php foreach ($tickets as $ticket) { ?>
                        <?php if ($ticket->status->id == $id) $count += 1; ?>
                    <?php } ?>
                    <tr>
                        <td><?php echo $name; ?></td>   
                        <td><?php echo $count; ?></td>
                    </tr>
                <?php } ?>
            </table>
        </h4>
        <h3></h3>
            <form action="../view/viewall.php" method="post" style="display: inline;">
                <button class="button button" style="display: inline;">Homepage</button>
            </form>
        </span>
    </div>
</body>
</html>